/* Copyright © Artur Maziarek MMXX
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
#pragma once

enum class ParamId
{
  CONTROLLER_MARK,
  EQUIPMENT_ID,
  DATE_TIME,
  TEMP_SENSOR01_OUT_ATS,
  TEMP_SENSOR03_KETTLE_KTS,
  TEMP_SENSOR05_TANK_STS1,
  TEMP_SENSOR5B_TANK2_STS2,
  TEMP_HOT_WATER_HIGH,
  TEMP_HOT_WATER_LOW,
  TEMP_SENSOR15_FUMES_AGTS,
  TEMP_RETURN_17A_RLTS,
  TEMP_SUPPLY_17B_VLTS,
  TEMP_SUPPLY_ATTACHED_EQUIPMENT,
  TEMP_SUPPLY_LOWPASS,
  TEMP_SUPPLY_DAMPED,
  TEMP_KETTLE1,
  TEMP_KETTLE2,
  TEMP_KETTLE3,
  TEMP_KETTLE4,
  TEMP_SUPPLY_A1M1,
  TEMP_SUPPLY_M2,
  TEMP_SUPPLY_M3,
  TEMP_RETURN_M2,
  TEMP_KETTLE,
  TEMP_KETTLE_LOWPASS,
  TEMP_TANK1_LOWPASS_STS1,
  TEMP_TANK2_LOWPASS_STS2,
  TEMP_FUMES_LOWPASS_AGTS,
  TEMP_RETURN_17A_LOWPASS,
  TEMP_RETURN_SUPPLY_17B_LOWPASS,
  TEMP_ROOM_A1M1_LOWPASS,
  TEMP_ROOM_M2_LOWPASS,
  TEMP_ROOM_M3_LOWPASS,
  TEMP_FUMES_MAX_ACHIEVED,
  // Temperatures – current set values
  TEMP_SETTING_SUPPLY_ATTACHED_EQUIPMENT,
  TEMP_SETTING_SUPPLY_A1M1,
  TEMP_SETTING_ROOM_M2,
  TEMP_SETTING_SUPPLY_M2,
  TEMP_SETTING_SUPPLY_M3,
  TEMP_SETTING_RETURN_ATTACHED_EQUIPMENT,
  TEMP_SETTING_KETTLE,
  TEMP_SETTING_KETTLE1,
  TEMP_SETTING_KETTLE2,
  TEMP_SETTING_KETTLE3,
  TEMP_SETTING_KETTLE4,
  // Burner
  BURNER_CURRENT_STAGE,
  POWER_CURRENT_OF_BURNER /* % */,
  BURNER_FAULT,
  BURNER_STATE_STAGE1,
  BURNER_STATE_STAGE2,
  BURNER_OIL_USAGE,
  BURNER_STARTS_COUNT,
  WORKING_HOURS_BURNER_STAGE1 /* sec */,
  WORKING_HOURS_BURNER_STAGE2 /* sec */,
  // Solar
  TEMP_SOLAR_COLLECTOR,
  WORKING_HOURS_SOLAR,
  SOLAR_RELOADING_PREASSURE,
  PUMP_SOLAR,
  TEMP_SOLAR_TANK,
  TEMP_SOLAR_TANK_DUMPED,
  SOLAR_WARM_AMOUNT /* kWh */,
  SOLAR_INFO,
  SOLAR_DAILY_PRODUCTION /* Wh */,
  // State of pumps, mixers, etc.
  PUMP_TAP_WATER_TANK_LOADING_ON_OFF,
  PUMP_TAP_WATER_CIRCULATION_ON_OFF,
  MIXER_POSITION_M1 /* % */,
  MIXER_POSITION_M2 /* % */,
  MIXER_POSITION_M3 /* % */,
  PUMP_HEATING_CIRCUIT_A1M1,
  PUMP_HEATING_CIRCUIT_M2,
  PUMP_HEATING_CIRCUIT_M3,
  VALVE_FLAP_POSITION /* % */,
  PUMP_INTERNAL,
  SWITCHING_VALVE_HEATING_HOT_WATER,
  ROTATION_SPEED_SETTING_PUMP_HEATING_CIRCUIT_M2 /* RPM */,
  ROTATION_SPEED_SETTING_PUMP_INTERNAL /* RPM */,
  // Operating conditions (read only)
  FAILURE_COLLECTION,
  CURRENT_OPERATING_MODE_A1M1,
  CURRENT_OPERATING_MODE_M2,
  CURRENT_OPERATING_MODE_M3,
  POWER_OF_ATTACHED_EQUIPMENT1 /* % */,
  POWER_OF_KETTLE /* % */,
  // Functions
  TEMP_FUMES_MAX_ACHIEVED_RESET,
  // Service (read/write)
  MODE_NORMAL_OPERATION,
  MODE_NORMAL_OPERATION_V200KO1B_KO2B,
  MODE_SAVING,
  MODE_PARTY,
  HEAING_CURVE_LEVEL,
  HEATING_CURVE_TILT,
  TEMP_SETTING_ROOM,
  TEMP_SETTING_ROOM_REDUCED,
  TEMP_SETTING_PARTY_MODE,
  // Details of operating conditions (read only)
  OPERATING_MODE_2,
  TIMER_RISING_PHASE,
  HOT_WATER_RELEASE,
  PUMP_HEATING_CIRCUIT,
  ROOM_DISCONNECTION,
  TEMP_SETTING_2_ROOM,
  FROST_HAZARD,
  PUMP_HOT_WATER,
  TEMP_SUPPLY_PRIMARY_CIRCUIT_AIR,
  TEMP_RETURN_PRIMARY_CIRCUIT_AIR,
  TEMP_SUPPLY_PRIMARY_CIRCUIT_WATER,
  TEMP_RETURN_PRIMARY_CIRCUIT_WATER,
  PRESSURE_EVAPORATOR,
  PRESSURE_CONDENSATOR,
  TEMP_EVAPORATOR,
  WORKING_HOURS_COMPRESSOR /* sec */,
  WORKING_HOURS_PRIMARY_SOURCE /* sec */,
  WORKING_HOURS_SECONDARY_SOURCE /* sec */,
  WORKING_HOURS_PASSTHROUGH_HEATER_STAGE1 /* sec */,
  WORKING_HOURS_PASSTHROUGH_HEATER_STAGE2 /* sec */,
  WORKING_HOURS_HEATING_CIRCUIT_A1 /* sec */,
  WORKING_HOURS_HEATING_CIRCUIT_M2 /* sec */,
  WORKING_HOURS_HEATING_CIRCUIT_M3 /* sec */,
  WORKING_HOURS_ADDITIONAL_OUTPUT_Z_PUMP /* sec */,
  WORKING_HOURS_COLLECTIVE_REPORT /* sec */,
  WORKING_HOURS_SWITCHING_VALVE_HEATING_HOT_WATER /* sec */,
  WORKING_HOURS_TANK_LOADING_PUMP /* sec */,
  SWITCH_COUNT_COMPRESSOR,
  SWITCH_COUNT_PRIMARY_SOURCE,
  SWITCH_COUNT_SECONDARY_SOURCE,
  SWITCH_COUNT_PASSTHROUGH_HEATER_STAGE1,
  SWITCH_COUNT_PASSTHROUGH_HEATER_STAGE2,
  SWITCH_COUNT_HEATING_CIRCUIT_A1,
  SWITCH_COUNT_HEATING_CIRCUIT_M2,
  SWITCH_COUNT_HEATING_CIRCUIT_M3,
  SWITCH_COUNT_ADDITIONAL_OUTPUT_Z_PUMP,
  SWITCH_COUNT_COLLECTIVE_REPORT,
  SWITCH_COUNT_SWITCHING_VALVE_HEATING_HOT_WATER,
  SWITCH_COUNT_TANK_LOADING_PUMP,
  STATUS_ON_OFF_COMPRESSOR,
  STATUS_ON_OFF_PRIMARY_SOURCE,
  STATUS_ON_OFF_SECONDARY_SOURCE,
  STATUS_ON_OFF_PASSTHROUGH_HEATER_STAGE1,
  STATUS_ON_OFF_PASSTHROUGH_HEATER_STAGE2,
  STATUS_ON_OFF_HEATING_CIRCUIT_A1,
  STATUS_ON_OFF_HEATING_CIRCUIT_M2,
  STATUS_ON_OFF_HEATING_CIRCUIT_M3,
  STATUS_ON_OFF_ADDITIONAL_OUTPUT_Z_PUMP,
  STATUS_ON_OFF_COLLECTIVE_REPORT,
  STATUS_ON_OFF_SWITCHING_VALVE_HEATING_HOT_WATER,
  STATUS_ON_OFF_TANK_LOADING_PUMP,
  // Pellet and wood kettle additional parameters
  TEMP_CUSHION_DUMPED_HIGH,
  TEMP_CUSHION_DUMPED_LOW,
  TEMP_FLAME,
  TEMP_INSET,
  LAMBDA_PROBE /* % */,
  POSITION_PRIMARY_AIR_FLAP,
  POSITION_SECONDARY_AIR_FLAP,
  ROTATION_SPEED_SETTING,
  ROTATION_SPEED_VALUE,
  FUEL_USAGE /* kg */,
  // Data from vcontrold XMLs
  TEMP_SETTING_HOT_WATER /* deg C */,
  TEMP_SETTING_PARTY_MODE_M2 /* deg C */,
  MODE_PARTY_M2,
  // Data as used in "v-control - 1.2.5" software
  // VScotHO1
  TEMP_KETTLE_CURRENT,            /* °C */
  TEMP_KETTLE_TARGET,             /* °C */
  TEMP_SUPPLY_CURRENT,            /* °C */
  TEMP_SUPPLY_TARGET,             /* °C */
  TEMP_RETURN,                    /* °C */
  TEMP_OUTSIDE,                   /* °C */
  TEMP_OUTSIDE_DEWPOINT,          /* °C */
  TEMP_TAP_WATER_TANK_CURRENT,    /* °C */
  TEMP_TAP_WATER_TANK_TARGET,     /* °C */
  TEMP_ROOM_CURRENT,              /* °C */
  TEMP_ROOM_TARGET,               /* °C */
  TEMP_ROOM_DAY_NORMAL_TARGET,    /* °C */
  TEMP_ROOM_NIGHT_REDUCED_TARGET, /* °C */
  BURNER_CURRENT_POWER,           /* % */
  BURNER_WORKING_SECONDS,
  BURNER_WORKING_SECONDS_2,
  KETTLE_OPERATION_MODE,
  SWITCHING_VALVE_POSITION,
  EXTERNAL_LOCK,
  EXTERNAL_REQUEST,
};

enum class KettleOperationMode : uint8_t
{
  offStandby                    = 0,
  tapWaterTankHeatingOnly       = 1,
  tapWaterTankAndCentralHeating = 2,
  alwaysDayNormalMode           = 3,
  alwaysNightReducedMode        = 4,
};

enum class SwitchingValvePosition : uint8_t
{
  centralHeating      = 1,
  tapWaterTankLoading = 3,
};
