#include <ParamDefinition.h>
#include <climits>
#include <cfloat>

const ParamDefinition paramDefinition =
{
  {ControllerId::V333MW1, {
    {ParamId::TEMP_SENSOR01_OUT_ATS                 , {true, false, 0x0800, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR03_KETTLE_KTS              , {true, false, 0x0802, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR05_TANK_STS1               , {true, false, 0x0804, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR5B_TANK2_STS2              , {true, false, 0x0806, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_RLTS                  , {true, false, 0x080A, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_17B_VLTS                  , {true, false, 0x080C, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_ATTACHED_EQUIPMENT        , {true, false, 0x0950, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_LOWPASS                   , {true, false, 0x5525, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_DAMPED                    , {true, false, 0x5527, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE1                          , {true, false, 0xA202, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE2                          , {true, false, 0xA242, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE3                          , {true, false, 0xA282, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE4                          , {true, false, 0xA2C2, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_A1M1                      , {true, false, 0x2900, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_M2                        , {true, false, 0x3900, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_M3                        , {true, false, 0x4900, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE_LOWPASS                   , {true, false, 0x0810, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1               , {true, false, 0x0812, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK2_LOWPASS_STS2               , {true, false, 0x0814, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_LOWPASS               , {true, false, 0x0818, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_SUPPLY_17B_LOWPASS        , {true, false, 0x081A, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_ROOM_A1M1_LOWPASS                , {true, false, 0x0896, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_ROOM_M2_LOWPASS                  , {true, false, 0x0898, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_ROOM_M3_LOWPASS                  , {true, false, 0x089A, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_ATTACHED_EQUIPMENT, {true, false, 0x5600, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_A1M1              , {true, false, 0x2544, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_M2                , {true, false, 0x3544, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_M3                , {true, false, 0x4544, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_RETURN_ATTACHED_EQUIPMENT, {true, false, 0x56A0, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE1                  , {true, false, 0xA226, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE2                  , {true, false, 0xA266, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE3                  , {true, false, 0xA2A6, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE4                  , {true, false, 0xA2E6, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::PUMP_TANK_LOADING                     , {true, false, 0x0845, 1 , 1  , 0      , 1      }},
    {ParamId::PUMP_CIRCULATION                      , {true, false, 0x0846, 1 , 1  , 0      , 1      }},
    {ParamId::MIXER_POSITION_M1/*%*/                , {true, false, 0x254C, 1 , 2  , INT_MIN, INT_MAX}},
    {ParamId::MIXER_POSITION_M2/*%*/                , {true, false, 0x354C, 1 , 2  , INT_MIN, INT_MAX}},
    {ParamId::MIXER_POSITION_M3/*%*/                , {true, false, 0x454C, 1 , 2  , INT_MIN, INT_MAX}},
    {ParamId::PUMP_HEATING_CIRCUIT_A1M1             , {true, false, 0x2906, 1 , 1  , 0      , 1      }},
    {ParamId::PUMP_HEATING_CIRCUIT_M2               , {true, false, 0x3906, 1 , 1  , 0      , 1      }},
    {ParamId::PUMP_HEATING_CIRCUIT_M3               , {true, false, 0x4906, 1 , 1  , 0      , 1      }},
    {ParamId::FAILURE_COLLECTION                    , {true, false, 0x0847, 1 , 1  , 0      , 1      }},
    {ParamId::CURRENT_OPERATING_MODE_A1M1           , {true, false, 0x2500, 22, 1  , INT_MIN, INT_MAX}},
    {ParamId::CURRENT_OPERATING_MODE_M2             , {true, false, 0x3500, 22, 1  , INT_MIN, INT_MAX}},
    {ParamId::CURRENT_OPERATING_MODE_M3             , {true, false, 0x4500, 22, 1  , INT_MIN, INT_MAX}},
    {ParamId::POWER_OF_ATTACHED_EQUIPMENT1/*%*/     , {true, false, 0xA38F, 2 , 2  , 0      , 100    }},
    {ParamId::MODE_NORMAL_OPERATION                 , {true, true , 0x2301, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::MODE_SAVING                           , {true, true , 0x2302, 1 , 1  , 0      , 1      }},
    {ParamId::MODE_PARTY                            , {true, true , 0x2303, 1 , 1  , 0      , 1      }},
    {ParamId::HEAING_CURVE_LEVEL                    , {true, true , 0x2304, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::HEATING_CURVE_TILT                    , {true, true , 0x2305, 1 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_ROOM                     , {true, true , 0x2306, 1 , 1  , 3      , 37     }},
    {ParamId::TEMP_SETTING_ROOM_REDUCED             , {true, true , 0x2307, 1 , 1  , 3      , 37     }},
    {ParamId::TEMP_SETTING_PARTY_MODE               , {true, true , 0x2308, 1 , 1  , 3      , 37     }},
    {ParamId::OPERATING_MODE_2                      , {true, false, 0x2501, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::TIMER_RISING_PHASE                    , {true, false, 0x2502, 4 , 10 , INT_MIN, INT_MAX}},
    {ParamId::HOT_WATER_RELEASE                     , {true, false, 0x2508, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::PUMP_HEATING_CIRCUIT                  , {true, false, 0x250A, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::ROOM_DISCONNECTION                    , {true, false, 0x250B, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_2_ROOM                   , {true, false, 0x250C, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::FROST_HAZARD                          , {true, false, 0x2510, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_HOT_WATER/*degC*/        , {true, true , 0x6300, 1 , 1  , INT_MIN, INT_MAX}},
  }},
  {ControllerId::V100GC1, {
    {ParamId::TEMP_SENSOR03_KETTLE_KTS          , {true, false, 0x0802, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR05_TANK_STS1           , {true, false, 0x0804, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR5B_TANK2_STS2          , {true, false, 0x0806, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR15_FUMES_AGTS          , {true, false, 0x0808, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_RLTS              , {true, false, 0x080A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_17B_VLTS              , {true, false, 0x080C, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE                       , {true, false, 0xA309, 2 , 100 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE_LOWPASS               , {true, false, 0x0810, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1           , {true, false, 0x0812, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK2_LOWPASS_STS2           , {true, false, 0x0814, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_FUMES_LOWPASS_AGTS           , {true, false, 0x0816, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_LOWPASS           , {true, false, 0x0818, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_SUPPLY_17B_LOWPASS    , {true, false, 0x081A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_FUMES_MAX_ACHIEVED           , {true, false, 0x089F, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_A1M1          , {true, false, 0x2544, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE               , {true, false, 0x555A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::BURNER_CURRENT_STAGE              , {true, false, 0x551E, 1 , 1   , 0      , 2      }},
    {ParamId::POWER_CURRENT_OF_BURNER/*%*/      , {true, false, 0x55E3, 1 , 2   , INT_MIN, INT_MAX}},
    {ParamId::BURNER_FAULT                      , {true, false, 0x0883, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_STATE_STAGE1               , {true, false, 0x0842, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_STATE_STAGE2               , {true, false, 0x0849, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_OIL_USAGE                  , {true, false, 0x7574, 4 , 1000, INT_MIN, INT_MAX}},
    {ParamId::BURNER_STARTS_COUNT               , {true, false, 0x088A, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE1/*sec*/, {true, false, 0x0886, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE2/*sec*/, {true, false, 0x08A3, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::VALVE_FLAP_POSITION/*%*/          , {true, false, 0x5555, 1 , 2   , INT_MIN, INT_MAX}},
    {ParamId::FAILURE_COLLECTION                , {true, false, 0x0847, 1 , 1   , 0      , 1      }},
    {ParamId::CURRENT_OPERATING_MODE_A1M1       , {true, false, 0x2500, 22, 1   , INT_MIN, INT_MAX}},
    {ParamId::POWER_OF_ATTACHED_EQUIPMENT1/*%*/ , {true, false, 0xA38F, 2 , 2   , 0      , 100    }},
    {ParamId::POWER_OF_KETTLE/*%*/              , {true, false, 0xA305, 2 , 2   , 0      , 100    }},
    {ParamId::TEMP_FUMES_MAX_ACHIEVED_RESET     , {true, true , 0x08A1, 2 , 1   , INT_MIN, INT_MAX}},
    {ParamId::OPERATING_MODE_2                  , {true, false, 0x2501, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::HOT_WATER_RELEASE                 , {true, false, 0x2508, 1 , 1   , INT_MIN, INT_MAX}},

  }},
  {ControllerId::VDensHO1, {
    {ParamId::TEMP_RETURN_17A_RLTS                                 , {true, false, 0x0808, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_LOWPASS                                  , {true, false, 0x5525, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_DAMPED                                   , {true, false, 0x5527, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_M2                                       , {true, false, 0x3900, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE                                          , {true, false, 0xA393, 2 , 100, INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE_LOWPASS                                  , {true, false, 0x0810, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1                              , {true, false, 0x0812, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK2_LOWPASS_STS2                              , {true, false, 0x0814, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_A1M1                             , {true, false, 0x2544, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_M2                               , {true, false, 0x3544, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE                                  , {true, false, 0x555A, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::BURNER_STARTS_COUNT                                  , {true, false, 0x088A, 4 , 1  , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE1/*sec*/                   , {true, false, 0x0886, 4 , 1  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SOLAR_COLLECTOR                                 , {true, false, 0x6564, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_SOLAR                                  , {true, false, 0x6568, 2 , 1  , INT_MIN, INT_MAX}},
    {ParamId::SOLAR_RELOADING_PREASSURE                            , {true, false, 0x6551, 1 , 1  , 0      , 1      }},
    {ParamId::PUMP_SOLAR                                           , {true, false, 0x6552, 1 , 1  , 0      , 1      }},
    {ParamId::TEMP_SOLAR_TANK                                      , {true, false, 0x6566, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::SOLAR_WARM_AMOUNT/*kWh*/                             , {true, false, 0x6560, 4 , 1  , INT_MIN, INT_MAX}},
    {ParamId::PUMP_TANK_LOADING                                    , {true, false, 0x6513, 1 , 1  , 0      , 1      }},
    {ParamId::PUMP_CIRCULATION                                     , {true, false, 0x6515, 1 , 1  , 0      , 1      }},
    {ParamId::PUMP_HEATING_CIRCUIT_A1M1                            , {true, false, 0x7663, 2 , 1  , 0      , 100    }},
    {ParamId::PUMP_HEATING_CIRCUIT_M2                              , {true, false, 0x7665, 2 , 1  , 0      , 100    }},
    {ParamId::PUMP_INTERNAL                                        , {true, false, 0x7660, 2 , 1  , 0      , 100    }},
    {ParamId::SWITCHING_VALVE_HEATING_HOT_WATER                    , {true, false, 0x0A10, 1 , 1  , 0      , 3      }},
    {ParamId::ROTATION_SPEED_SETTING_PUMP_HEATING_CIRCUIT_M2/*RPM*/, {true, false, 0x0A3B, 1 , 1  , 0      , 100    }},
    {ParamId::ROTATION_SPEED_SETTING_PUMP_INTERNAL/*RPM*/          , {true, false, 0x0A3C, 1 , 1  , 0      , 100    }},
    {ParamId::FAILURE_COLLECTION                                   , {true, false, 0x0A82, 1 , 1  , 0      , 1      }},
    {ParamId::CURRENT_OPERATING_MODE_A1M1                          , {true, false, 0x2500, 22, 1  , INT_MIN, INT_MAX}},
    {ParamId::POWER_OF_ATTACHED_EQUIPMENT1/*%*/                    , {true, false, 0xA38F, 2 , 2  , 0      , 100    }},
    {ParamId::MODE_NORMAL_OPERATION                                , {true, true , 0x2323, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::MODE_SAVING                                          , {true, true , 0x2302, 1 , 1  , 0      , 1      }},
    {ParamId::MODE_PARTY                                           , {true, true , 0x2303, 1 , 1  , 0      , 1      }},
    {ParamId::OPERATING_MODE_2                                     , {true, false, 0x2501, 1 , 1  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_2_ROOM                                  , {true, false, 0x250C, 2 , 10 , INT_MIN, INT_MAX}},
    {ParamId::FROST_HAZARD                                         , {true, false, 0x2510, 1 , 1  , INT_MIN, INT_MAX}},
  }},
  {ControllerId::V200GW1, {
    {ParamId::TEMP_SENSOR01_OUT_ATS             , {true, false, 0x0800, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR03_KETTLE_KTS          , {true, false, 0x0802, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR05_TANK_STS1           , {true, false, 0x0804, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR5B_TANK2_STS2          , {true, false, 0x0806, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR15_FUMES_AGTS          , {true, false, 0x0808, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_RLTS              , {true, false, 0x080A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_17B_VLTS              , {true, false, 0x080C, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_LOWPASS               , {true, false, 0x5525, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_DAMPED                , {true, false, 0x5527, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE                       , {true, false, 0xA309, 2 , 100 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE_LOWPASS               , {true, false, 0x0810, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1           , {true, false, 0x0812, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK2_LOWPASS_STS2           , {true, false, 0x0814, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_FUMES_LOWPASS_AGTS           , {true, false, 0x0816, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_LOWPASS           , {true, false, 0x0818, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_SUPPLY_17B_LOWPASS    , {true, false, 0x081A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_ROOM_A1M1_LOWPASS            , {true, false, 0x0896, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_FUMES_MAX_ACHIEVED           , {true, false, 0x089F, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_A1M1          , {true, false, 0x2544, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE               , {true, false, 0x555A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::BURNER_CURRENT_STAGE              , {true, false, 0x551E, 1 , 1   , 0      , 2      }},
    {ParamId::POWER_CURRENT_OF_BURNER/*%*/      , {true, false, 0x55E3, 1 , 2   , INT_MIN, INT_MAX}},
    {ParamId::BURNER_FAULT                      , {true, false, 0x0883, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_STATE_STAGE1               , {true, false, 0x0842, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_STATE_STAGE2               , {true, false, 0x0849, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_OIL_USAGE                  , {true, false, 0x7574, 4 , 1000, INT_MIN, INT_MAX}},
    {ParamId::BURNER_STARTS_COUNT               , {true, false, 0x088A, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE1/*sec*/, {true, false, 0x0886, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE2/*sec*/, {true, false, 0x08A3, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::PUMP_TANK_LOADING                 , {true, false, 0x0845, 1 , 1   , 0      , 1      }},
    {ParamId::PUMP_CIRCULATION                  , {true, false, 0x0846, 1 , 1   , 0      , 1      }},
    {ParamId::MIXER_POSITION_M1/*%*/            , {true, false, 0x254C, 1 , 2   , INT_MIN, INT_MAX}},
    {ParamId::PUMP_HEATING_CIRCUIT_A1M1         , {true, false, 0x2906, 1 , 1   , 0      , 1      }},
    {ParamId::VALVE_FLAP_POSITION/*%*/          , {true, false, 0x5555, 1 , 2   , INT_MIN, INT_MAX}},
    {ParamId::FAILURE_COLLECTION                , {true, false, 0x0847, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::CURRENT_OPERATING_MODE_A1M1       , {true, false, 0x2500, 22, 1   , INT_MIN, INT_MAX}},
    {ParamId::POWER_OF_ATTACHED_EQUIPMENT1/*%*/ , {true, false, 0xA38F, 2 , 2   , 0      , 100    }},
    {ParamId::POWER_OF_KETTLE/*%*/              , {true, false, 0xA305, 2 , 2   , 0      , 100    }},
    {ParamId::TEMP_FUMES_MAX_ACHIEVED_RESET     , {true, true , 0x08A1, 2 , 1   , INT_MIN, INT_MAX}},
    {ParamId::MODE_NORMAL_OPERATION             , {true, true , 0x2301, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::MODE_SAVING                       , {true, true , 0x2302, 1 , 1   , 0      , 1      }},
    {ParamId::MODE_PARTY                        , {true, true , 0x2303, 1 , 1   , 0      , 1      }},
    {ParamId::HEAING_CURVE_LEVEL                , {true, true , 0x2304, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::HEATING_CURVE_TILT                , {true, true , 0x2305, 1 , 10  , INT_MIN, INT_MAX}},
    {ParamId::OPERATING_MODE_2                  , {true, false, 0x2501, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::TIMER_RISING_PHASE                , {true, false, 0x2502, 4 , 10  , INT_MIN, INT_MAX}},
    {ParamId::HOT_WATER_RELEASE                 , {true, false, 0x2508, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::PUMP_HEATING_CIRCUIT              , {true, false, 0x250A, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::ROOM_DISCONNECTION                , {true, false, 0x250B, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_2_ROOM               , {true, false, 0x250C, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::FROST_HAZARD                      , {true, false, 0x2510, 1 , 1   , INT_MIN, INT_MAX}},
  }},
  {ControllerId::V200KW1, {
    {ParamId::TEMP_SENSOR01_OUT_ATS                , {true, false, 0x0800, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR03_KETTLE_KTS             , {true, false, 0x0802, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR05_TANK_STS1              , {true, false, 0x0804, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR15_FUMES_AGTS             , {true, false, 0x0808, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_RLTS                 , {true, false, 0x080A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_17B_VLTS                 , {true, false, 0x080C, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_LOWPASS                  , {true, false, 0x5525, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_DAMPED                   , {true, false, 0x5527, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_M2                       , {true, false, 0x3900, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_M2                       , {true, false, 0x3902, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE                          , {true, false, 0xA309, 2 , 100 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE_LOWPASS                  , {true, false, 0x0810, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1              , {true, false, 0x0812, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK2_LOWPASS_STS2              , {true, false, 0x0814, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_FUMES_LOWPASS_AGTS              , {true, false, 0x0816, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_LOWPASS              , {true, false, 0x0818, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_SUPPLY_17B_LOWPASS       , {true, false, 0x081A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_ROOM_A1M1_LOWPASS               , {true, false, 0x0896, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_FUMES_MAX_ACHIEVED              , {true, false, 0x089F, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_A1M1             , {true, false, 0x2544, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE                  , {true, false, 0x555A, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::BURNER_CURRENT_STAGE                 , {true, false, 0x551E, 1 , 1   , 0      , 2      }},
    {ParamId::POWER_CURRENT_OF_BURNER /* % */      , {true, false, 0x55E3, 1 , 2   , INT_MIN, INT_MAX}},
    {ParamId::BURNER_FAULT                         , {true, false, 0x0883, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_STATE_STAGE1                  , {true, false, 0x0842, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_STATE_STAGE2                  , {true, false, 0x0849, 1 , 1   , 0      , 1      }},
    {ParamId::BURNER_OIL_USAGE                     , {true, false, 0x7574, 4 , 1000, INT_MIN, INT_MAX}},
    {ParamId::BURNER_STARTS_COUNT                  , {true, false, 0x088A, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE1 /* sec */, {true, false, 0x08A7, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE2 /* sec */, {true, false, 0x08AB, 4 , 1   , INT_MIN, INT_MAX}},
    {ParamId::PUMP_TANK_LOADING                    , {true, false, 0x0845, 1 , 1   , 0      , 1      }},
    {ParamId::PUMP_CIRCULATION                     , {true, false, 0x0846, 1 , 1   , 0      , 1      }},
    {ParamId::MIXER_POSITION_M1 /* % */            , {true, false, 0x254C, 1 , 2   , INT_MIN, INT_MAX}},
    {ParamId::PUMP_HEATING_CIRCUIT_A1M1            , {true, false, 0x2906, 1 , 1   , 0      , 1      }},
    {ParamId::VALVE_FLAP_POSITION /* % */          , {true, false, 0x5555, 1 , 2   , INT_MIN, INT_MAX}},
    {ParamId::FAILURE_COLLECTION                   , {true, false, 0x0847, 1 , 1   , 0      , 1      }},
    {ParamId::CURRENT_OPERATING_MODE_A1M1          , {true, false, 0x2500, 22, 1   , INT_MIN, INT_MAX}},
    {ParamId::CURRENT_OPERATING_MODE_M2            , {true, false, 0x3500, 22, 1   , INT_MIN, INT_MAX}},
    {ParamId::POWER_OF_ATTACHED_EQUIPMENT1 /* % */ , {true, false, 0xA38F, 2 , 2   , 0      , 100    }},
    {ParamId::POWER_OF_KETTLE /* % */              , {true, false, 0xA305, 2 , 2   , 0      , 100    }},
    {ParamId::TEMP_FUMES_MAX_ACHIEVED_RESET        , {true, true , 0x08A1, 2 , 1   , INT_MIN, INT_MAX}},
    {ParamId::MODE_NORMAL_OPERATION                , {true, true , 0x2301, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::MODE_SAVING                          , {true, true , 0x2302, 1 , 1   , 0      , 1      }},
    {ParamId::MODE_PARTY                           , {true, true , 0x2303, 1 , 1   , 0      , 1      }},
    {ParamId::HEAING_CURVE_LEVEL                   , {true, true , 0x2304, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::HEATING_CURVE_TILT                   , {true, true , 0x2305, 1 , 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_ROOM                    , {true, true , 0x2306, 1 , 1   , 3      , 37     }},
    {ParamId::TEMP_SETTING_ROOM_REDUCED            , {true, true , 0x2307, 1 , 1   , 3      , 37     }},
    {ParamId::TEMP_SETTING_PARTY_MODE              , {true, true , 0x2308, 1 , 1   , 3      , 37     }},
    {ParamId::OPERATING_MODE_2                     , {true, false, 0x2501, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::TIMER_RISING_PHASE                   , {true, false, 0x2502, 4 , 10  , INT_MIN, INT_MAX}},
    {ParamId::HOT_WATER_RELEASE                    , {true, false, 0x2508, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::PUMP_HEATING_CIRCUIT                 , {true, false, 0x250A, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::ROOM_DISCONNECTION                   , {true, false, 0x250B, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_2_ROOM                  , {true, false, 0x250C, 2 , 10  , INT_MIN, INT_MAX}},
    {ParamId::FROST_HAZARD                         , {true, false, 0x2510, 1 , 1   , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_HOT_WATER /* deg C */   , {true, true , 0x6300, 1 , 1   , INT_MIN, INT_MAX}},
  }},
  {ControllerId::V200KO1B, {
    {ParamId::TEMP_SENSOR01_OUT_ATS                , {true, false, 0x0800, 2, 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR03_KETTLE_KTS             , {true, false, 0x0802, 2, 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR05_TANK_STS1              , {true, false, 0x0804, 2, 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1              , {true, false, 0x0812, 2, 10  , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE                  , {true, false, 0x5502, 2, 10  , INT_MIN, INT_MAX}},
    {ParamId::BURNER_OIL_USAGE                     , {true, false, 0x7574, 4, 1000, INT_MIN, INT_MAX}},
    {ParamId::BURNER_STARTS_COUNT                  , {true, false, 0x088A, 4, 1   , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE1 /* sec */, {true, false, 0x8A7 , 4, 1   , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SOLAR_COLLECTOR                 , {true, false, 0x6564, 2, 10  , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_SOLAR                  , {true, false, 0x6568, 2, 1   , INT_MIN, INT_MAX}},
    {ParamId::SOLAR_RELOADING_PREASSURE            , {true, false, 0x6551, 1, 1   , 0      , 1      }},
    {ParamId::TEMP_SOLAR_TANK                      , {true, false, 0x6566, 2, 10  , INT_MIN, INT_MAX}},
    {ParamId::SOLAR_WARM_AMOUNT /* kWh */          , {true, false, 0x6560, 4, 1   , INT_MIN, INT_MAX}},
    {ParamId::SOLAR_DAILY_PRODUCTION /* Wh */      , {true, false, 0xCF30, 4, 1   , INT_MIN, INT_MAX}},
    {ParamId::PUMP_TANK_LOADING                    , {true, false, 0x0845, 1, 1   , 0      , 1      }},
    {ParamId::MODE_NORMAL_OPERATION_V200KO1B_KO2B  , {true, true , 0x2323, 1, 1   , INT_MIN, INT_MAX}},
  }},
  {ControllerId::VScotHO1, {
    {ParamId::TEMP_SENSOR5B_TANK2_STS2                                , {true, false, 0x0806, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR15_FUMES_AGTS                                , {true, false, 0x0808, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_LOWPASS                                     , {true, false, 0x5525, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_DAMPED                                      , {true, false, 0x5527, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_M2                                          , {true, false, 0x3900, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE_LOWPASS                                     , {true, false, 0x0810, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1                                 , {true, false, 0x0812, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK2_LOWPASS_STS2                                 , {true, false, 0x0814, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_ROOM_A1M1_LOWPASS                                  , {true, false, 0x0896, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_ROOM_M2_LOWPASS                                    , {true, false, 0x0898, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_A1M1                                , {true, false, 0x2544, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_ROOM_M2                                    , {true, false, 0x350C, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_M2                                  , {true, false, 0x3544, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE                                     , {true, false, 0x555A, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::POWER_CURRENT_OF_BURNER /* % */                         , {true, false, 0xA38F, 1 , 2 , INT_MIN, INT_MAX}},
    {ParamId::BURNER_STARTS_COUNT                                     , {true, false, 0x088A, 4 , 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE1 /* sec */                   , {true, false, 0x08A7, 4 , 1 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SOLAR_COLLECTOR                                    , {true, false, 0x6564, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_SOLAR                                     , {true, false, 0x6568, 2 , 1 , INT_MIN, INT_MAX}},
    {ParamId::SOLAR_RELOADING_PREASSURE                               , {true, false, 0x6551, 1 , 1 , 0      , 1      }},
    {ParamId::PUMP_SOLAR                                              , {true, false, 0x6552, 1 , 1 , 0      , 1      }},
    {ParamId::TEMP_SOLAR_TANK                                         , {true, false, 0x6566, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::SOLAR_WARM_AMOUNT /* kWh */                             , {true, false, 0x6560, 4 , 1 , INT_MIN, INT_MAX}},
    {ParamId::SOLAR_INFO                                              , {true, false, 0x7754, 1 , 1 , INT_MIN, INT_MAX}},
    {ParamId::PUMP_TANK_LOADING                                       , {true, false, 0x0845, 1 , 1 , 0      , 1      }},
    {ParamId::PUMP_CIRCULATION                                        , {true, false, 0x0846, 1 , 1 , 0      , 1      }},
    {ParamId::MIXER_POSITION_M1 /* % */                               , {true, false, 0x254C, 1 , 2 , INT_MIN, INT_MAX}},
    {ParamId::PUMP_HEATING_CIRCUIT_M2                                 , {true, false, 0x3906, 1 , 1 , 0      , 1      }},
    {ParamId::VALVE_FLAP_POSITION /* % */                             , {true, false, 0x5555, 1 , 2 , INT_MIN, INT_MAX}},
    {ParamId::ROTATION_SPEED_SETTING_PUMP_HEATING_CIRCUIT_M2 /* RPM */, {true, false, 0x0A3B, 1 , 1 , 0      , 100    }},
    {ParamId::ROTATION_SPEED_SETTING_PUMP_INTERNAL /* RPM */          , {true, false, 0x0A3C, 1 , 1 , 0      , 100    }},
    {ParamId::FAILURE_COLLECTION                                      , {true, false, 0x0847, 1 , 1 , 0      , 1      }},
    {ParamId::CURRENT_OPERATING_MODE_A1M1                             , {true, false, 0x2500, 22, 1 , INT_MIN, INT_MAX}},
    {ParamId::CURRENT_OPERATING_MODE_M2                               , {true, false, 0x3500, 22, 1 , INT_MIN, INT_MAX}},
    {ParamId::POWER_OF_ATTACHED_EQUIPMENT1 /* % */                    , {true, false, 0xA38F, 2 , 2 , 0      , 100    }},
    {ParamId::POWER_OF_KETTLE /* % */                                 , {true, false, 0xA305, 2 , 2 , 0      , 100    }},
    {ParamId::TEMP_FUMES_MAX_ACHIEVED_RESET                           , {true, true , 0x08A1, 2 , 1 , 0      , 1      }},
    {ParamId::MODE_NORMAL_OPERATION                                   , {true, true , 0x2301, 1 , 1 , INT_MIN, INT_MAX}},
    {ParamId::MODE_SAVING                                             , {true, true , 0x2302, 1 , 1 , 0      , 1      }},
    {ParamId::MODE_PARTY                                              , {true, true , 0x2303, 1 , 1 , 0      , 1      }},
    {ParamId::OPERATING_MODE_2                                        , {true, false, 0x2501, 1 , 1 , INT_MIN, INT_MAX}},
    {ParamId::TIMER_RISING_PHASE                                      , {true, false, 0x2502, 4 , 10, INT_MIN, INT_MAX}},
    {ParamId::HOT_WATER_RELEASE                                       , {true, false, 0x2508, 1 , 1 , INT_MIN, INT_MAX}},
    {ParamId::PUMP_HEATING_CIRCUIT                                    , {true, false, 0x250A, 1 , 1 , INT_MIN, INT_MAX}},
    {ParamId::ROOM_DISCONNECTION                                      , {true, false, 0x250B, 1 , 1 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_2_ROOM                                     , {true, false, 0x250C, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::FROST_HAZARD                                            , {true, false, 0x2510, 1 , 1 , INT_MIN, INT_MAX}},
  }},
  {ControllerId::VBC550, {
    {ParamId::TEMP_SENSOR01_OUT_ATS                , {true, false, 0x0800, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR05_TANK_STS1              , {true, false, 0x0804, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR5B_TANK2_STS2             , {true, false, 0x0806, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR15_FUMES_AGTS             , {true, false, 0x0808, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_LOWPASS                  , {true, false, 0x080E, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_A1M1                     , {true, false, 0x2900, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1              , {true, false, 0x0814, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::BURNER_STARTS_COUNT                  , {true, false, 0x088A, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE1 /* sec */, {true, false, 0x08A7, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SOLAR_COLLECTOR                 , {true, false, 0x6564, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_SOLAR                  , {true, false, 0x6568, 2, 1 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SOLAR_TANK_DUMPED               , {true, false, 0x081A, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::SOLAR_WARM_AMOUNT /* kWh */          , {true, false, 0x6560, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::MODE_NORMAL_OPERATION                , {true, true , 0x2301, 1, 1 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_CUSHION_DUMPED_HIGH             , {true, false, 0x0810, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_CUSHION_DUMPED_LOW              , {true, false, 0x0812, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE                          , {true, false, 0x0B12, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_FLAME                           , {true, false, 0x0B14, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_INSET                           , {true, false, 0x0B16, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::LAMBDA_PROBE /* % */                 , {true, false, 0x0B18, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::POSITION_PRIMARY_AIR_FLAP            , {true, false, 0x0B1A, 1, 1 , 0      , 100    }},
    {ParamId::POSITION_SECONDARY_AIR_FLAP          , {true, false, 0x0B1B, 1, 1 , 0      , 100    }},
    {ParamId::ROTATION_SPEED_SETTING               , {true, false, 0x0B1C, 2, 1 , 0      , 3000   }},
    {ParamId::ROTATION_SPEED_VALUE                 , {true, false, 0x0B1E, 2, 1 , 0      , 3000   }},
    {ParamId::POWER_OF_KETTLE /* % */              , {true, false, 0x0B20, 1, 1 , 0      , 100    }},
    {ParamId::FUEL_USAGE /* kg */                  , {true, false, 0x08B0, 4, 1 , INT_MIN, INT_MAX}},
  }},
  {ControllerId::VPlusHO1, {
    {ParamId::TEMP_SUPPLY_LOWPASS                  , {true, false, 0x5525, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_DAMPED                   , {true, false, 0x5527, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_M2                       , {true, false, 0x3900, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_KETTLE_LOWPASS                  , {true, false, 0x0810, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK1_LOWPASS_STS1              , {true, false, 0x0812, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_TANK2_LOWPASS_STS2              , {true, false, 0x0814, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_FUMES_LOWPASS_AGTS              , {true, false, 0x0816, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_LOWPASS              , {true, false, 0x0818, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_KETTLE                  , {true, false, 0x555A, 2 , 10, INT_MIN, INT_MAX}},
    {ParamId::BURNER_STARTS_COUNT                  , {true, false, 0x088A, 4 , 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_BURNER_STAGE1 /* sec */, {true, false, 0x0886, 4 , 1 , INT_MIN, INT_MAX}},
    {ParamId::CURRENT_OPERATING_MODE_A1M1          , {true, false, 0x2500, 22, 1 , INT_MIN, INT_MAX}},
  }},
  {ControllerId::V200WO1, {
    {ParamId::TEMP_SENSOR01_OUT_ATS                                    , {true, false, 0x0101, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SENSOR05_TANK_STS1                                  , {true, false, 0x010B, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_HOT_WATER_HIGH                                      , {true, false, 0x010D, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_HOT_WATER_LOW                                       , {true, false, 0x010E, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_ATTACHED_EQUIPMENT                           , {true, false, 0x010A, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_M2                                           , {true, false, 0x0114, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_M3                                           , {true, false, 0x0115, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_M3                                   , {true, false, 0x1004, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SOLAR_COLLECTOR                                     , {true, false, 0x0111, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SOLAR_TANK                                          , {true, false, 0x0113, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_ROOM                                        , {true, true , 0x2000, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_ROOM_REDUCED                                , {true, true , 0x2001, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_PARTY_MODE                                  , {true, true , 0x2022, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::HEAING_CURVE_LEVEL                                       , {true, true , 0x2006, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::HEATING_CURVE_TILT                                       , {true, true , 0x2007, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_PRIMARY_CIRCUIT_AIR                          , {true, false, 0x0103, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_PRIMARY_CIRCUIT_AIR                          , {true, false, 0x0104, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_PRIMARY_CIRCUIT_WATER                        , {true, false, 0x0105, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_PRIMARY_CIRCUIT_WATER                        , {true, false, 0x0106, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::PRESSURE_EVAPORATOR                                      , {true, false, 0x0680, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::PRESSURE_CONDENSATOR                                     , {true, false, 0x0682, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_EVAPORATOR                                          , {true, false, 0x0102, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_COMPRESSOR /* sec */                       , {true, false, 0x0580, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_PRIMARY_SOURCE /* sec */                   , {true, false, 0x0582, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_SECONDARY_SOURCE /* sec */                 , {true, false, 0x0584, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_PASSTHROUGH_HEATER_STAGE1 /* sec */        , {true, false, 0x0588, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_PASSTHROUGH_HEATER_STAGE2 /* sec */        , {true, false, 0x0589, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_HEATING_CIRCUIT_A1 /* sec */               , {true, false, 0x058D, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_HEATING_CIRCUIT_M2 /* sec */               , {true, false, 0x058E, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_HEATING_CIRCUIT_M3 /* sec */               , {true, false, 0x058F, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_ADDITIONAL_OUTPUT_Z_PUMP /* sec */         , {true, false, 0x0590, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_COLLECTIVE_REPORT /* sec */                , {true, false, 0x0591, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_SWITCHING_VALVE_HEATING_HOT_WATER /* sec */, {true, false, 0x0594, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::WORKING_HOURS_TANK_LOADING_PUMP /* sec */                , {true, false, 0x0596, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_COMPRESSOR                                  , {true, false, 0x0500, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_PRIMARY_SOURCE                              , {true, false, 0x0502, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_SECONDARY_SOURCE                            , {true, false, 0x0504, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_PASSTHROUGH_HEATER_STAGE1                   , {true, false, 0x0508, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_PASSTHROUGH_HEATER_STAGE2                   , {true, false, 0x0509, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_HEATING_CIRCUIT_A1                          , {true, false, 0x050D, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_HEATING_CIRCUIT_M2                          , {true, false, 0x050E, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_HEATING_CIRCUIT_M3                          , {true, false, 0x050F, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_ADDITIONAL_OUTPUT_Z_PUMP                    , {true, false, 0x0510, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_COLLECTIVE_REPORT                           , {true, false, 0x0511, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_SWITCHING_VALVE_HEATING_HOT_WATER           , {true, false, 0x0514, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_TANK_LOADING_PUMP                           , {true, false, 0x0516, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::STATUS_ON_OFF_COMPRESSOR                                 , {true, false, 0x0400, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_PRIMARY_SOURCE                             , {true, false, 0x0402, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_SECONDARY_SOURCE                           , {true, false, 0x0404, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_PASSTHROUGH_HEATER_STAGE1                  , {true, false, 0x0408, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_PASSTHROUGH_HEATER_STAGE2                  , {true, false, 0x0409, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_HEATING_CIRCUIT_A1                         , {true, false, 0x040D, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_HEATING_CIRCUIT_M2                         , {true, false, 0x040E, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_HEATING_CIRCUIT_M3                         , {true, false, 0x040F, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_ADDITIONAL_OUTPUT_Z_PUMP                   , {true, false, 0x0410, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_COLLECTIVE_REPORT                          , {true, false, 0x0411, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_SWITCHING_VALVE_HEATING_HOT_WATER          , {true, false, 0x0414, 1, 1 , 0      , 1      }},
    {ParamId::STATUS_ON_OFF_TANK_LOADING_PUMP                          , {true, false, 0x0416, 1, 1 , 0      , 1      }},
  }},
  {ControllerId::Vitocal200S, {
    {ParamId::TEMP_SENSOR01_OUT_ATS                          , {true, false, 0x0101, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_HOT_WATER_HIGH                            , {true, false, 0x010D, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_17A_RLTS                           , {true, false, 0x0106, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_17B_VLTS                           , {true, false, 0x0105, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_SETTING_SUPPLY_ATTACHED_EQUIPMENT         , {true, false, 0x1800, 2, 1 , INT_MIN, INT_MAX}},
    {ParamId::TEMP_SUPPLY_PRIMARY_CIRCUIT_WATER              , {true, false, 0x0105, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::TEMP_RETURN_PRIMARY_CIRCUIT_WATER              , {true, false, 0x0106, 2, 10, INT_MIN, INT_MAX}},
    {ParamId::SWITCH_COUNT_SECONDARY_SOURCE                  , {true, false, 0x0504, 4, 1 , INT_MIN, INT_MAX}},
    {ParamId::STATUS_ON_OFF_SWITCHING_VALVE_HEATING_HOT_WATER, {true, false, 0x0494, 2, 1 , INT_MIN, INT_MAX}},
  }},
};
